---
title: "Ch05 Time as a Complementary Variable"
output:
  html_document:
    keep_md: yes
---


## 1. Trendanalyzer
### - vertical and horizontal axes
### - bubble size
### - color
### - time variable

---

### 1.1. Polylines 
```{r}
##################################################################
## Initial configuration
##################################################################
## Clone or download the repository and set the working directory
## with setwd to the folder where the repository is located.

library(lattice)
library(ggplot2)
library(latticeExtra)
library(zoo)
setwd("~/R//visual/part3/ch5/")

##################################################################
## Polylines
##################################################################

load('CO2.RData')
str(CO2data)
head(CO2data)
summary(CO2data)

## ggplot2 version
ggplot(data=CO2data, aes(x=CO2.capita, y=GNI.capita,
                         color=Country.Name)) +
  xlab("CO2 emissions (metric tons per capita)") +
  ylab("GNI per capita, PPP (current international $)") +
  geom_point() + geom_path() + theme_bw()

```

---

### 1.2. Choosing Colors 

### - http://colorbrewer2.org/

```{r}

library(RColorBrewer)

nCountries <- nlevels(CO2data$Country.Name)
nCountries

pal <- brewer.pal(n=5, 'Set1')
pal

pal <- rep(pal, length = nCountries)
pal

## Rank of average values of CO2 per capita
CO2mean <- aggregate(CO2.capita ~ Country.Name, data=CO2data, FUN=mean)
CO2mean

palOrdered <- pal[rank(CO2mean$CO2.capita)]
palOrdered

CO2capita <- CO2data[, c('Country.Name', 'Year', 'CO2.capita')]
CO2capita

CO2capita <- reshape(CO2capita, idvar='Country.Name', timevar='Year', direction='wide')
CO2capita

hCO2 <- hclust(dist(CO2capita[, -1]))

oldpar <- par(mar=c(0, 2, 0, 0) + .1)

plot(hCO2, labels=CO2capita$Country.Name,
     xlab='', ylab='', sub='', main='')
par(oldpar)

idx <- match(levels(CO2data$Country.Name), 
             CO2capita$Country.Name[hCO2$order])

levels(CO2data$Country.Name)

CO2capita$Country.Name[hCO2$order]

idx

palOrdered <- pal[idx]
palOrdered

gCO2.capita <- ggplot(data=CO2data, aes(x=CO2.capita, y=GNI.capita,
                                        color=Country.Name)) +
  geom_point() + geom_path() +
  scale_color_manual(values=palOrdered, guide=FALSE) +
  xlab('CO2 emissions (metric tons per capita)') +
  ylab('GNI per capita, PPP (current international $)') +
  theme_bw()

gCO2.capita

```

---

### 1.3. Lavels to Show Time Information

```{r}
gCO2.capita <- gCO2.capita + geom_text(aes(label=Year), colour='gray',
                                       size=2.5, hjust=0, vjust=0)

gCO2.capita
```

---

### 1.4. Country Names : Positioning Labels
### - http://directlabels.r-forge.r-project.org/docs/index.html

```{r}
library(directlabels)

direct.label(gCO2.capita, method='extreme.grid')
```

---

### 1.5. A Panel for Each Year

```{r}

ggplot(data=CO2data, aes(x=CO2.capita, y=GNI.capita, colour=Country.Name)) +
  facet_wrap(~ Year) + geom_point(pch=19) + 
  xlab('CO2 emissions (metric tons per capita)') +
  ylab('GNI per capita, PPP (current international $)') +
  theme_bw()

##################################################################
## Using variable size to encode an additional variable
##################################################################

library(classInt)
z <- CO2data$CO2.PPP
z

intervals <- classIntervals(z, n=4, style='fisher')
intervals

nInt <- length(intervals$brks) - 1
intervals$brks
length(intervals$brks)
nInt

cex.key <- seq(0.5, 1.8, length=nInt)
cex.key

idx <- findCols(intervals)
idx

head(CO2data)
CO2data$cexPoints <- cex.key[idx]
head(CO2data)

CO2capita <- ggplot(data=CO2data, aes(x=CO2.capita, y=GNI.capita, colour=Country.Name)) +
  facet_wrap(~ Year) + geom_point(aes(size=cexPoints), pch=19) +
  xlab('CO2 emissions (metric tons per capita)') +
  ylab('GNI per capita, PPP (current international $)') +
  theme_bw()

CO2capita

direct.label(CO2capita, list(cex = 0.3, smart.grid))


### direct.label(p, list("top.points", rot=45, fontsize=25, fontface="bold", fontfamily="serif", alpha=0.5))
```

---

### 1.6. Travelling bubbles

```{r}

library(gridSVG)

xyplot(GNI.capita ~ CO2.capita, data=CO2data,
       subset=Year==2000, groups=Country.Name,
       ## The limits of the graphic are defined
       ## with the entire dataset
       xlim=extendrange(CO2data$CO2.capita),
       ylim=extendrange(CO2data$GNI.capita),
       panel=function(x, y, ..., subscripts, groups) {
         color <- palOrdered[groups[subscripts]]
         radius <- CO2data$CO2.PPP[subscripts]
         ## Size of labels
         cex <- 1.1*sqrt(radius)
         ## Bubbles
         grid.circle(x, y, default.units="native",
                     r=radius*unit(.25, "inch"),
                     name=trellis.grobname("points", type="panel"),
                     gp=gpar(col=color,
                             ## Fill color ligther than border
                             fill=adjustcolor(color, alpha=.5),
                             lwd=2))
         ## Country labels
         grid.text(label=groups[subscripts],
                   x=unit(x, 'native'),
                   ## Labels above each bubble
                   y=unit(y, 'native') + 1.5 * radius *unit(.25, 'inch'),
                   name=trellis.grobname('labels', type='panel'),
                   gp=gpar(col=color, cex=cex))
       })

## Duration in seconds of the animation
duration <- 20

nCountries <- nlevels(CO2data$Country.Name)
years <- unique(CO2data$Year)
nYears <- length(years)

## Intermediate positions of the bubbles
x_points <- animUnit(unit(CO2data$CO2.capita, 'native'),
                     id=rep(seq_len(nCountries), each=nYears))
y_points <- animUnit(unit(CO2data$GNI.capita, 'native'),
                     id=rep(seq_len(nCountries), each=nYears))
## Intermediate positions of the labels
y_labels <- animUnit(unit(CO2data$GNI.capita, 'native') +
                       1.5 * CO2data$CO2.PPP * unit(.25, 'inch'),
                     id=rep(seq_len(nCountries), each=nYears))
## Intermediate sizes of the bubbles
size <- animUnit(CO2data$CO2.PPP * unit(.25, 'inch'),
                 id=rep(seq_len(nCountries), each=nYears))

grid.animate(trellis.grobname("points", type="panel", row=1, col=1),
             duration=duration,
             x=x_points,
             y=y_points,
             r=size,
             rep=TRUE)

grid.animate(trellis.grobname("labels", type="panel", row=1, col=1),
             duration=duration,
             x=x_points,
             y=y_labels,
             rep=TRUE)

countries <- unique(CO2data$Country.Name)
URL <- paste('http://en.wikipedia.org/wiki/', countries, sep='')
grid.hyperlink(trellis.grobname('points', type='panel', row=1, col=1),
               URL, group=FALSE)

visibility <- matrix("hidden", nrow=nYears, ncol=nYears)
diag(visibility) <- "visible"
yearText <- animateGrob(garnishGrob(textGrob(years, .9, .15,
                                             name="year",
                                             gp=gpar(cex=2, col="grey")),
                                    visibility="hidden"),
                        duration=20,
                        visibility=visibility,
                        rep=TRUE)
grid.draw(yearText)

```

```{r}
library(googleVis)
pgvis <- gvisMotionChart(CO2data, idvar = "Country.Name", timevar = "Year")
plot(pgvis)
```


