---
title: "ch5.Mathematical Models for Network Graphs"
author: "Park, Jung Eun"
date: "Thursday, March 19, 2015"
output:
  html_document:
    keep_md: yes
---

5.2 Classical Random Graph Models

- 에르되스&레니의 무작위네트워크
- erdos.renyi.game(N,p)

```{r}
library(sand)
set.seed(42)
g.er <- erdos.renyi.game(100,0.02)
plot(g.er, layout = layout.circle, vertex.label=NA)
#?erdos.renyi.game

str(g.er)
is.connected(g.er)

table(sapply(decompose.graph(g.er), vcount))

mean(degree(g.er))
hist(degree(g.er), col="lightblue",
     xlab="Degree", ylab="Frequency", main="")

average.path.length(g.er)
diameter(g.er)
transitivity(g.er)

```

5.3 Generalized Random Graph Models

```{r}
degs <- c(2,2,2,2,3,3,3,3)
g1 <- degree.sequence.game(degs, method="vl")
g2 <- degree.sequence.game(degs, method="vl")
plot(g1, vertex.label=NA)
plot(g2, vertex.label=NA)
graph.isomorphic(g1, g2)
c(ecount(g1), ecount(g2), mean(degree(g1)), mean(degree(g2)))
```

```{r}
data(yeast)
degs <- degree(yeast)
fake.yeast <- degree.sequence.game(degs, method=c("vl"))
all(degree(yeast) == degree(fake.yeast))
ecount(yeast)
ecount(fake.yeast)
vcount(yeast)
vcount(fake.yeast)
mean(degree(yeast))
mean(degree(fake.yeast))
diameter(yeast)
diameter(fake.yeast)
transitivity(yeast)
transitivity(fake.yeast)
```

5.4 Network Graph Models Based on Mechanisms

5.4.1 Small-World Models

```{r}
g.ws <- watts.strogatz.game(1, 25, 5, 0.05)
plot(g.ws, layout=layout.circle, vertex.label=NA)
vcount(g.ws)

g.lat100 <- watts.strogatz.game(1, 100, 5, 0)
plot(g.lat100, layout=layout.circle, vertex.label=NA)
transitivity(g.lat100)

diameter(g.lat100)
average.path.length(g.lat100)

g.ws100 <- watts.strogatz.game(1, 100, 5, 0.05)
plot(g.ws100, layout=layout.circle, vertex.label=NA)
diameter(g.ws100)

average.path.length(g.ws100)
transitivity(g.ws100)
ecount(g.lat100)
ecount(g.ws100)
```

```{r}
steps <- seq(-4, -0.5, 0.1)
len <- length(steps)
cl <- numeric(len)
apl <- numeric(len)
ntrials <- 100
for (i in (1:len)) {
   cltemp <- numeric(ntrials)
   apltemp <- numeric(ntrials)
   for (j in (1:ntrials)) {
     g <- watts.strogatz.game(1, 1000, 10, 10^steps[i])
     cltemp[j] <- transitivity(g)
     apltemp[j] <- average.path.length(g)
   }
   cl[i] <- mean(cltemp)
   apl[i] <- mean(apltemp)
 }

plot(steps, cl/max(cl), ylim=c(0, 1), lwd=3, type="l", 
   col="blue", xlab=expression(log[10](p)),
   ylab="Clustering and Average Path Length")
lines(steps, apl/max(apl), lwd=3, col="red")
```


