---
title: "Ch06"
output:
  html_document:
    keep_md: yes
---


## 6. SIAR
- The Agroclimatic Information System for Irrigation (SIAR) : DB

---

### 6.1. Daily data of different meteorological variables
- http://eportal.magrama.gob.es/websiar

```{r}
library(zoo)
setwd("~/R//visual//part3//ch6")
aranjuez <- read.zoo("aranjuez.gz", index.column = 3, format ="%d/%m/%Y",
                     fileEncoding = 'UTF-16LE',
                     header = TRUE, fill=TRUE,
                     sep = ';', dec = ',', as.is = TRUE)
str(aranjuez)
head(aranjuez)

aranjuez <- aranjuez[, -c(1:4)]

head(aranjuez)
summary(aranjuez)

```

```{r}
names(aranjuez) <- c("TempAvg", "TempMax", "TempMin", "HumidAvg", "HumidMax",
                     "WindAvg", "WindMax", "Radiation", "Rain", "ET")
summary(aranjuez)

aranjuezClean <- within(as.data.frame(aranjuez),{
  TempMin[TempMin > 40] <- NA
  HumidMax[HumidMax > 100] <- NA
  WindAvg[WindAvg > 10] <- NA
  WindMax[WindMax > 10] <- NA
})
summary(aranjuezClean)
aranjuez <- zoo(aranjuezClean, index(aranjuez))

head(aranjuez)
str(aranjuez)
```

----

### 6.2. Unemployment in the USA
```{r}
unemployUSA <- read.csv("unemployUSA.csv")
head(unemployUSA)
str(unemployUSA)

nms <- unemployUSA$Series.ID
nms
annualCols <- 14 + 13*(0:12)
annualCols

unemployUSA <- as.data.frame(t(unemployUSA[,-c(1, annualCols)]))
head(unemployUSA)

names(unemployUSA) <- substring(nms, 7)
head(unemployUSA)

```

```{r}
library(zoo)

Sys.setlocale("LC_TIME", "C")
idx <- as.yearmon(row.names(unemployUSA), format = "%b.%Y")
unemployUSA <- zoo(unemployUSA, idx)
unemployUSA

isNA <- apply(is.na(unemployUSA), 1, any)
unemployUSA <- unemployUSA[!isNA,]
unemployUSA
```

### 6.3. Gross National Income and CO2 Emissions
```{r}
library(WDI)

CO2data <- WDI(indicator = c("EN.ATM.CO2E.PC", "EN.ATM.CO2E.PP.GD",
                             "NY.GNP.MKTP.PP.CD", "NY.GNP.PCAP.PP.CD"),
               start=2000, end=2011,
               country = c("BR", "CN", "DE", "ES", "FI", "FR",
                           "GR", "IN", "NO", "US"))

head(CO2data)
str(CO2data)
summary(CO2data)

names(CO2data) <- c("iso2c", "Country.Name", "Year", "CO2.capita", "CO2.PPP",
                    "GNI.PPP", "GNI.capita")

head(CO2data)

isNA <- apply(is.na(CO2data), 1, any)
CO2data <- CO2data[!isNA,]

CO2data$Country.Name <- factor(CO2data$Country.Name)

head(CO2data)
str(CO2data)
summary(CO2data)

```

